require('dotenv').config();
const cloudinary = require('cloudinary').v2;

async function uploadToCloudinary(url, filter_no, options) {

    try {

        const grover_image_url_array = url.split('/');
        grover_image_url_array.splice(7, filter_no);
        grover_image_url = grover_image_url_array.join('/');
        const image = await cloudinary.uploader.upload(grover_image_url, options);
        // console.log();
        // console.log("** File Upload (Promise)");
        // console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        // console.log("* " + image.public_id);
        // console.log("* " + image.secure_url);
        return image.secure_url;
    } catch (error) {
        console.error(error)
    }

}

module.exports = uploadToCloudinary;